version: '3'
services:
  db:
   image: postgres:latest
   ports:
     - "5433:5432"
   environment:
         - POSTGRES_DB=contacts_db
         - POSTGRES_USER=dev
         - POSTGRES_PASSWORD=

  api:
    build:
      context: .
    ports:
      - "5000:5000"
    depends_on:
      - db
      - telegraf

  grafana:
      image: matisq/grafana:latest
      ports:
          - 3000:3000
      links:
          - influxdb:influxdb
      environment:
          GF_INSTALL_PLUGINS: "grafana-influxdb-08-datasource,natel-influx-admin-panel"
          GF_SECURITY_ADMIN_USER: admin
          GF_SECURITY_ADMIN_PASSWORD: admin
          GF_SECURITY_SECRET_KEY: grafana
          GF_USERS_ALLOW_SIGN_UP: "true"
          GF_USERS_ALLOW_ORG_CREATE: "true"
          GF_AUTH_ANONYMOUS_ENABLED: "true"
          GF_AUTH_ANONYMOUS_ORG_NAME: grafana
          GF_DASHBOARDS_JSON_ENABLED: "true"
          GF_DASHBOARDS_JSON_PATH: /opt/grafana
      volumes:
          - grafana-data
      restart: always
  grafana-data:
      image: busybox
      tty: true
      volumes:
          - /var/lib/grafana
          - /var/log/grafana
          - /var/lib/grafana/plugins


  influxdb:
      image: matisq/influxdb:latest
      ports:
          - 8083:8083
          - 8086:8086
      volumes:
          - influxdb-data

      environment:
          INFLUX_DATABASE: "telegraf"
          INLFUX_ADMIN_USER: "grafana"
          INFLUX_ADMIN_PASS: "grafana"

  influxdb-data:
      image: busybox
      tty: true
      volumes:
          - /var/lib/influxdb

  telegraf:
      image: telegraf:1.4.0
      volumes:
        - ./tig-stack/etc/telegraf.conf:/etc/telegraf/telegraf.conf
      links:
        - influxdb
      ports:
        - "8092:8092/udp"
        - "8094:8094"
        - "8125:8125/udp"